FROM python:3.8-slim

# Set the working directory within the container
RUN mkdir /app
WORKDIR /app

# Copy the necessary files and directories into the container
COPY backend/requirements.txt /app/requirements.txt
COPY backend/app.py /app/app.py
COPY backend/tour /app/tour

# Upgrade pip and install Python dependencies
RUN pip3 install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Expose port 5000 for the Flask application
EXPOSE 5000

# Define the command to run the Flask application using Gunicorn
CMD ["gunicorn", "application:app", "-b", "0.0.0.0:5000", "-w", "4"]